### PR TITLE
Nikita branch readme changes

### PR DESCRIPTION
**Pull request by mathur-nikita**
- Initial changes to readme
- new ERD

### CODE REVIEW

**Review by kjkubik — APPROVED** [review]
thank you Nikita! You are awesome!

**Review by kjkubik — APPROVED** [review]
thank you Nikita! You are awesome!

**Review by kjkubik — COMMENTED** [review]
Thank you for doing such a good job!

**Review by kjkubik — APPROVED** [review]
thanks!

**Review by kjkubik — APPROVED** [review]

**Review by armandolatigo — APPROVED** [review]
reviewed in real time, good to go.

**Pull request merged**
